export const CompaniesConstants = {
  COMPANIES_CALLBACK_REQUEST: 'COMPANIES_CALLBACK_REQUEST',
  COMPANIES_CALLBACK_ERROR: 'COMPANIES_CALLBACK_ERROR',
  COMPANIES_CALLBACK_SUCCESS: 'COMPANIES_CALLBACK_SUCCESS',
}
